import { createSlice } from "@reduxjs/toolkit";
import { PURGE } from "redux-persist";
import { nanoid } from "@reduxjs/toolkit"; // Use nanoid for unique IDs if available in RTK, or separate.
// RTK exports nanoid. If not, use Date.now() + math random.
// Actually, simple Date.now is fine for local.

const initialState = {
    tasks: {}, // keyed by date string "YYYY-MM-DD" -> { sections: [ { id, title, tasks: [] } ] }
};

const DEFAULT_SECTIONS = [
    { id: 'todo', title: '', tasks: [] },
];

const todoSlice = createSlice({
    name: "todo",
    initialState,
    reducers: {
        // Migration helper: Call this on app start
        migrateLegacyData: (state) => {
            const keys = Object.keys(state.tasks);
            keys.forEach(key => {
                // Simple regex for YYYY-MM-DD
                if (/^\d{4}-\d{2}-\d{2}$/.test(key)) {
                    // It's a date key, migrate it
                    const newId = Date.now().toString() + Math.random().toString(36).substr(2, 5);
                    const oldData = state.tasks[key];

                    // Create new structure
                    state.tasks[newId] = {
                        id: newId,
                        date: key, // Use the key as the date
                        createdAt: Date.now(), // Set migration time as creation time
                        title: '', // No title for legacy
                        sections: oldData.sections || [] // Preserve sections
                    };

                    // Clean up legacy fallback if 'must_do' style existed inside sections logic (handled in old addTask)
                    // If oldData didn't have sections but had must_do arrays, we should have migrated them before, 
                    // but let's strictly assume sections exist or we initialize defaults.
                    if (!state.tasks[newId].sections || state.tasks[newId].sections.length === 0) {
                        state.tasks[newId].sections = JSON.parse(JSON.stringify(DEFAULT_SECTIONS));
                    }

                    // Delete old key
                    delete state.tasks[key];
                }
            });
        },

        addNote: (state, action) => {
            const { date, title, type } = action.payload;
            const newId = Date.now().toString() + Math.random().toString(36).substr(2, 5);
            const now = Date.now();
            state.tasks[newId] = {
                id: newId,
                date: date,
                createdAt: now,
                updatedAt: now,
                type: type || 'list',
                title: title || "",
                sections: JSON.parse(JSON.stringify(DEFAULT_SECTIONS)),
                body: ""
            };
        },

        // Helper to add note with specific ID (generated by UI)
        createNote: (state, action) => {
            const { id, date, title, type } = action.payload;
            const now = Date.now();
            state.tasks[id] = {
                id,
                date,
                createdAt: now,
                updatedAt: now,
                type: type || 'list',
                title: title || "",
                sections: JSON.parse(JSON.stringify(DEFAULT_SECTIONS)),
                body: ""
            };
        },

        updateNoteTitle: (state, action) => {
            const { noteId, title } = action.payload;
            if (state.tasks[noteId]) {
                state.tasks[noteId].title = title;
                state.tasks[noteId].updatedAt = Date.now();
            }
        },

        updateNoteAudio: (state, action) => {
            const { noteId, audioUri, audioDuration } = action.payload;
            if (state.tasks[noteId]) {
                state.tasks[noteId].audioUri = audioUri;
                state.tasks[noteId].audioDuration = audioDuration;
                state.tasks[noteId].updatedAt = Date.now();
            }
        },

        updateNoteBody: (state, action) => {
            const { noteId, body } = action.payload;
            if (state.tasks[noteId]) {
                state.tasks[noteId].body = body;
                state.tasks[noteId].updatedAt = Date.now();
            }
        },

        updateNoteDate: (state, action) => {
            const { noteId, date } = action.payload;
            if (state.tasks[noteId]) {
                state.tasks[noteId].date = date;
                state.tasks[noteId].updatedAt = Date.now();
            }
        },

        addSection: (state, action) => {
            const { noteId, title } = action.payload;
            if (state.tasks[noteId]) {
                state.tasks[noteId].sections.push({
                    id: Date.now().toString() + Math.random().toString(36).substr(2, 5),
                    title,
                    tasks: []
                });
                state.tasks[noteId].updatedAt = Date.now();
            }
        },

        updateSectionTitle: (state, action) => {
            const { noteId, sectionId, title } = action.payload;
            if (state.tasks[noteId]) {
                const section = state.tasks[noteId].sections.find(s => s.id === sectionId);
                if (section) section.title = title;
                state.tasks[noteId].updatedAt = Date.now();
            }
        },

        deleteSection: (state, action) => {
            const { noteId, sectionId } = action.payload;
            if (state.tasks[noteId]) {
                state.tasks[noteId].sections = state.tasks[noteId].sections.filter(s => s.id !== sectionId);
                state.tasks[noteId].updatedAt = Date.now();
            }
        },

        addTask: (state, action) => {
            const { noteId, sectionId, text, time } = action.payload;
            if (state.tasks[noteId]) {
                const section = state.tasks[noteId].sections.find(s => s.id === sectionId);
                if (section) {
                    section.tasks.push({
                        id: Date.now().toString(),
                        text,
                        time,
                        completed: false,
                    });
                    state.tasks[noteId].updatedAt = Date.now();
                }
            }
        },

        toggleTask: (state, action) => {
            const { noteId, sectionId, id } = action.payload;
            if (state.tasks[noteId]) {
                const section = state.tasks[noteId].sections.find(s => s.id === sectionId);
                if (section) {
                    const task = section.tasks.find(t => t.id === id);
                    if (task) task.completed = !task.completed;
                    state.tasks[noteId].updatedAt = Date.now();
                }
            }
        },

        updateTask: (state, action) => {
            const { noteId, sectionId, id, text, time } = action.payload;
            if (state.tasks[noteId]) {
                const section = state.tasks[noteId].sections.find(s => s.id === sectionId);
                if (section) {
                    const task = section.tasks.find(t => t.id === id);
                    if (task) {
                        if (text !== undefined) task.text = text;
                        if (time !== undefined) task.time = time;
                        state.tasks[noteId].updatedAt = Date.now();
                    }
                }
            }
        },

        deleteTask: (state, action) => {
            const { noteId, sectionId, id } = action.payload;
            if (state.tasks[noteId]) {
                const section = state.tasks[noteId].sections.find(s => s.id === sectionId);
                if (section) {
                    section.tasks = section.tasks.filter(t => t.id !== id);
                    state.tasks[noteId].updatedAt = Date.now();
                }
            }
        },

        // Remove entire note if needed
        deleteNote: (state, action) => {
            const { noteId } = action.payload;
            delete state.tasks[noteId];
        }
    },
    extraReducers: (builder) => {
        builder.addCase(PURGE, (state) => {
            return initialState;
        });
    },
});

export const {
    createNote, addNote, updateNoteTitle, updateNoteDate, deleteNote, updateNoteBody, updateNoteAudio,
    addTask, toggleTask, deleteTask, updateTask, addSection, deleteSection, updateSectionTitle,
    migrateLegacyData
} = todoSlice.actions;
export default todoSlice.reducer;
